management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods:
          - GET
          - POST
        allowed-headers: "*"
spring:
  application:
    name: users
